# Generated by Django 2.0.5 on 2018-07-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ('-updated',)},
        ),
    ]
